"""Initial migration

Revision ID: 4bc6ebe6dbce
Revises: 
Create Date: 2026-02-23 10:46:12.662740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc6ebe6dbce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('revendedoras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('plano', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_table('revendedora_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revendedora_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['payment_providers.id'], ),
    sa.ForeignKeyConstraint(['revendedora_id'], ['revendedoras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revendedora_id', 'provider_id', name='uq_revendedora_provider_wallet')
    )
    op.create_table('vendas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revendedora_id', sa.UUID(), nullable=False),
    sa.Column('valor_total', sa.DECIMAL(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['revendedora_id'], ['revendedoras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_failures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_attempt', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['payment_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revendedora_id', sa.UUID(), nullable=False),
    sa.Column('venda_id', sa.UUID(), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('provider_payment_id', sa.Text(), nullable=True),
    sa.Column('valor_bruto', sa.DECIMAL(), nullable=False),
    sa.Column('taxa_plataforma', sa.DECIMAL(), nullable=False),
    sa.Column('taxa_provider', sa.DECIMAL(), nullable=False),
    sa.Column('valor_liquido_revendedora', sa.DECIMAL(), nullable=False),
    sa.Column('split_config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('webhook_recebido', sa.Boolean(), nullable=True),
    sa.Column('webhook_retries', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['payment_providers.id'], ),
    sa.ForeignKeyConstraint(['revendedora_id'], ['revendedoras.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacoes')
    op.drop_table('webhook_failures')
    op.drop_table('vendas')
    op.drop_table('revendedora_wallets')
    op.drop_table('revendedoras')
    op.drop_table('payment_providers')
    # ### end Alembic commands ###
